version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./node-test
          pkg-manager: npm
      - restore_cache:
          name: Restore saved cache
          key: v1-{{ checksum "package-lock.json" }}
      - run:
          app-dir: ./node-test
          command: npm ci
          name: Run install
      - run:
          app-dir: ./node-test
          command: npm run test
          name: Run tests
      - run:
          app-dir: ./node-test
          command: npm run build
          name: Build app
      - save_cache:
          name: Save npm package cache
          key: v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/node
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./node-test
            
workflows:
  test_my_app:
    jobs:
      - build_and_test
