version: 2.1

orbs:
  node: circleci/node@5.0.2
  
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - node/install-packages:
          pkg-manager: npm
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm test
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - node/install-packages:
          pkg-manager: npm
      - checkout
      - run: echo "build project"
      - npm install
      - npm run build
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
