name: reusable workflow terraform
  
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      secrets:
        token:
          required: true

jobs:
  run terraform:
    name: terraform ci/cd
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.token }}

    - name: Terraform format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.token }}
