name: "Workflow Dispatch"

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true
 
jobs:
  WorkflowDispatchPRButtonTesting:
    name: 'Test PR with button'
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    
    steps:
    - name: 'Verify deploy with PR number manually"
      uses: actions/github-script@v5
      id: verify_pr_number
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        result-encoding: string
        script: |
          const response = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.inputs.PR_number }}
          });
          
          // Check if the pull request is open
          if (response.data.number !== ${{ github.event.inputs.PR_number }}) {
            throw new Error('Pull request is not open or number is not valid!');
          } else {
            console.log("PR ref: " + response.data.head.ref);
            return response.data.head.ref;
          }
          
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_TF_SA_KEY }}

    - name: Terraform format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_TF_SA_KEY }}
